# Generated by Django 4.2 on 2023-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_category_alt_product_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Порядковий номер для зміни розташування на сайті"
            ),
        ),
    ]
